# Generated by Django 3.1 on 2020-08-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departameno',
            new_name='Departamento',
        ),
    ]
